Svwzioep notion 509
BasedHardware/Omi pull request #551
Opened 2024-08-08 06:37 UTC by beastoin

2024-08-08 06:49 UTC, beastoin commented on plugins/example/client.py
Remove this redundant, moved to oauth_client

2024-08-08 06:49 UTC, beastoin commented on plugins/example/main.py
> -            # .apt_install('libgl1-mesa-glx', 'libglib2.0-0')
revoke changes, formating

2024-08-08 06:49 UTC, beastoin commented on plugins/instructions/notion-crm-oauth/README.md
> +# Setting Up [Your Plugin Name]
where is the name ?

2024-08-08 06:49 UTC, beastoin commented on plugins/instructions/notion-crm-oauth/README.md
> +[Common issues and solutions]
remove this line, there have no issue now

2024-08-08 07:55 UTC, josancamon19 commented
Hi @beastoin this shouldn't be a new plugin. Please check the current plugins/example/auth/ folder in the repo.

There's an existing notion plugin, this should be a completion of that plugin.

2024-08-08 08:04 UTC, beastoin commented
> Hi @beastoin this shouldn't be a new plugin. Please check the current plugins/example/auth/ folder in the repo.
> 
> There's an existing notion plugin, this should be a completion of that plugin.

Hi @josancamon19,

Do you mean `plugins/example/basic_auth/` :? Actually, I used the pattern of the current Notion plugin in `plugins/example/basic_auth/`, then added the OAuth method and a prefix (/notion/) for the new OAuth Notion to ensure it does not break the current implementation.

So, should I update directly to basic_auth next?

2024-08-08 09:50 UTC, beastoin commented
Hi Joan,

A new commit just came in. Basically, we now just need to maintain one Notion plugin in `plugins/example/oauth`. The APIs will look like this:

<img width="1465" alt="Screenshot 2024-08-08 at 16 46 36" src="https://github.com/user-attachments/assets/c60e3d59-7e1f-4b02-a72e-bbc26fe82cde">

Feel free to ask for changes if needed ~
Good day!

2024-08-08 09:59 UTC, beastoin commented
Forgot to mention @josancamon19 , in case you need to discuss via chat, feel free to ping me on Discord at `@thinh`

> Hi Joan,
> 
> A new commit just came in. Basically, we now just need to maintain one Notion plugin in `plugins/example/oauth`. The APIs will look like this:
> <img alt="Screenshot 2024-08-08 at 16 46 36" width="1465" src="https://private-user-images.githubusercontent.com/4256921/356170926-c60e3d59-7e1f-4b02-a72e-bbc26fe82cde.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTEyODEsIm5iZiI6MTcyMzExMDk4MSwicGF0aCI6Ii80MjU2OTIxLzM1NjE3MDkyNi1jNjBlM2Q1OS03ZTFmLTRiMDItYTcyZS1iYmMyNmZlODJjZGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMDk1NjIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDRmNzdjZmViN2YzZjliZmU3MWYxODgxOWFhYmUxMTNlNzhjZWJlMGQ5M2ZiNzA5YjI5NTM0ZDNmY2Y4Y2Y4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A5eUj-qesxYFD3JsN1Fq7wca3dKOGR9LKykZI0GRzKI">
> 
> Feel free to ask for changes if needed ~ Good day!

2024-08-09 07:09 UTC, josancamon19 commented
Can you submit a video of this functionality?
Could be either from postman, browser or anywhere, thanks!

2024-08-09 07:10 UTC, josancamon19 commented
@beastoin

2024-08-09 07:11 UTC, beastoin commented
Ok sure, please wait me for 15m @josancamon19

2024-08-09 07:30 UTC, beastoin commented
Hi @josancamon19 new UAT just dropped, please take a look.

**UAT:**

1. Video demo (user view): 

https://github.com/user-attachments/assets/9277e8ab-9094-41ea-baa0-615f9b8a9195

2. System database:
<img width="834" alt="Screenshot 2024-08-09 at 14 27 15" src="https://github.com/user-attachments/assets/258bf06d-98eb-49b0-865b-f6e3a5b3b5a8">

3. You can try live version at modal.com https://beastoin--plugins-examples-plugins-app.modal.run/setup-notion-crm?uid=thinhcd9-14b4-4656-9b1f-30823d7dab3a

Good day :)

2024-08-09 21:12 UTC, josancamon19 commented on plugins/example/oauth/memory_created.py
> +    databaseOk = getNotion().getDatabase(database_id, notion_api_key)
Please do snake case naming convention everywhere.

2024-08-09 22:10 UTC, beastoin commented on plugins/example/oauth/memory_created.py
> +    databaseOk = getNotion().getDatabase(database_id, notion_api_key)
Yes, done. My fault 😵

2024-08-09 22:27 UTC, josancamon19 requested changes
https://github.com/user-attachments/assets/7f858d14-4e4a-4368-931c-052977db8b02


Besides those changes, it seems to be working properly!

2024-08-09 22:27 UTC, josancamon19 commented on plugins/example/oauth/memory_created.py
> +    database_id = databases[0].id
Can we include the db field validation here?

2024-08-09 22:27 UTC, josancamon19 commented on plugins/example/oauth_client.py
> +import os
Let's move this to oauth folder

2024-08-09 22:27 UTC, josancamon19 commented on plugins/example/oauth/memory_created.py
> +@router.post('/creds/notion-crm', response_class=HTMLResponse, tags=['oauth'])
do we still need this page?

2024-08-09 22:27 UTC, josancamon19 commented on plugins/example/oauth/memory_created.py
> +@router.post('/creds/notion-crm', response_class=HTMLResponse, tags=['oauth'])
this endpoint*?

2024-08-09 22:29 UTC, josancamon19 commented
There's a template option https://josancamon19.notion.site/a391a37323a74dbaa798fc02e8d61006?v=25ae8d3a8ff4471ba5ecccda4bd89425&pvs=4

But when I oauth and select the "Provided template, doesn't seem to work

2024-08-09 22:32 UTC, beastoin commented on plugins/example/oauth/memory_created.py
> +    database_id = databases[0].id
yes, of course

2024-08-09 22:34 UTC, beastoin commented
> There's a template option https://josancamon19.notion.site/a391a37323a74dbaa798fc02e8d61006?v=25ae8d3a8ff4471ba5ecccda4bd89425&pvs=4
> 
> But when I oauth and select the "Provided template, doesn't seem to work

Seems like the code was oudated v/s template, let me update 😀

<img width="921" alt="Screenshot 2024-08-10 at 05 33 04" src="https://github.com/user-attachments/assets/e3c00e2a-0c5a-4f26-9b1a-f27a31d70180">

2024-08-09 23:17 UTC, beastoin commented
Resolved/all. We are good now, please take a look @josancamon19 

![Screen Shot 2024-08-10 at 06 15 15](https://github.com/user-attachments/assets/dfff0518-015e-4dee-bb8b-b4bd5a04f65d)

<img width="1557" alt="Screenshot 2024-08-10 at 06 13 03" src="https://github.com/user-attachments/assets/389e9247-8cac-4fa7-9348-2b48b7720230">

2024-08-10 04:53 UTC, josancamon19 approved these changes

2024-08-10 04:53 UTC, merged

2024-08-13 20:16 UTC, kodjima33 commented
@beastoin Hey bro! We've sent bounty :) Thank you a lot for contributing! 

Can we chat asap? really realy curious to learn more about u! Just sent you a booking link and my phone number via email