screenpipe plugin 001
BasedHardware/omi pull request #582
Opened 2024-08-11 01:58 UTC by m13v

2024-08-11 08:02 UTC, josancamon19 requested changes
Pls include the json data in community-plugins.json.

Also the json is possibly wrongly formatted.

2024-08-13 06:47 UTC, josancamon19 requested changes

2024-08-13 06:47 UTC, josancamon19 commented on plugins/instructions/screenpipe/README.md
> +Get started with screenpipe:
Can you also include here, what's screenpipe and what this plugin does?

2024-08-15 03:02 UTC, m13v commented
made updates/changes

2024-08-17 04:14 UTC, m13v commented
resolved

2024-08-23 09:34 UTC, josancamon19 approved these changes

2024-08-23 09:35 UTC, merged

2024-08-23 09:45 UTC, m13v commented
🥳

On Fri, Aug 23, 2024 at 2:35 AM Joan Cabezas ***@***.***>
wrote:

> Merged #582 <https://github.com/BasedHardware/Omi/pull/582> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BasedHardware/Omi/pull/582#event-13990763633>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY62CDBL6ZB5YYNTSFGRCLDZS3677AVCNFSM6AAAAABMKJ4MWCVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTHE4TANZWGM3DGMY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2026-04-22 18:12 UTC, ellaaicare commented
## Correction Pipeline Analysis — April 22, 2026

### What I tested

Sent test payloads directly to the live n8n `conversation-correction` webhook endpoint. Results:

1. **Webhook IS reachable** — `POST https://n8n.ella-ai-care.com/webhook/conversation-correction` returns HTTP 202 ✅
2. **Immediate response**: `{\"status\":\"success\",\"trace_id\":\"...\"}` ✅
3. **BUT**: The live workflow does NOT write any correction file to OpenClaw workspace ❌
4. **AND**: The live workflow does NOT call OpenClaw `/observe` endpoint ❌

### Root cause

The **active n8n workflow is an empty stub** — it immediately returns `{"status":"success"}` without doing any actual work. The actual implementation in `services/n8n-workflows/conversation-correction-process.json` (write correction file → call OpenClaw `/workspace/{agentId}/write` → call `/observe`) has **not been deployed to n8n**.

### Verified pipeline works (for crypto plato user)

When I triggered a test with a valid UID (crypto plato's `5aGC5YE9BnhcSoTxxtT4ar6ILQy2`), the OpenClaw provision API logs show:
- `PUT /workspace/ella-omi-5agc5ye9bnhcsotxxtt4ar6ilqy2/write` → 200 OK
- `POST /workspace/ella-omi-5agc5ye9bnhcsotxxtt4ar6ilqy2/observe` → 200 OK
- Observer ran: prompt ~19K chars, model `minimax/MiniMax-M2.7`
- But Observer returned `[]` — no actions taken (likely because the correction file was never actually written)

### The fix needed

Deploy the `conversation-correction-process.json` workflow to n8n. This requires SSH access to `root@100.101.168.91` to update the n8n workflow.

### What works end-to-end today (for provisioned users)
- iOS → OMI backend `POST /v1/ella/conversations/{id}/corrections` ✅
- OMI backend → n8n `conversation-correction` webhook ✅
- n8n immediately returns 202 ✅
- OpenClaw Observer is reachable from n8n ✅
- BUT n8n workflow doesn't execute its logic (empty stub) ❌