Update community-plugins.json
BasedHardware/Omi pull request #595
Opened 2024-08-13 23:08 UTC by AlexTs10

Added the bookwatch plugin in the community-plugins.json

2024-08-15 02:55 UTC, josancamon19 requested changes

2024-08-15 02:55 UTC, josancamon19 commented on community-plugins.json
> +    "image": "https://cdn.prod.website-files.com/6696811effea0ba47d64eca9/66984b3ae54fc5b0fc78a34f_Bookwatch%20Logo%20Trademark%20(5).png",
This looks amazing!

Thank you @AlexTs10 for your first contribution!

A slight change, the image field, should be a file referenced in https://github.com/BasedHardware/Omi/tree/main/plugins/logos

Also, can you please submit a video showing off this? Thanks!

2024-08-16 21:47 UTC, AlexTs10 commented
Changed the image field, will also try to record a video.

2024-08-17 08:20 UTC, AlexTs10 commented
Is the video required in order to get accepted ?

2024-08-24 23:52 UTC, josancamon19 commented
Hi unfortunately yes, a video is reuqired to see how the plugin works, thanks @AlexTs10

2024-08-24 23:53 UTC, josancamon19 commented
or at least a video from postman requests

2024-08-27 21:11 UTC, AlexTs10 commented
Hey @josancamon19  added the video in the setup_instructions_file_path
Also you can check it here: https://drive.google.com/file/d/1zJqOfghhuBeLzu7XySpEZEIklnYndpdA/view?usp=sharing

Happy to answer any questions if needed.

2024-08-29 08:19 UTC, josancamon19 commented
LGTM

2024-08-29 08:19 UTC, josancamon19 approved these changes

2024-08-29 08:20 UTC, josancamon19 approved these changes

2024-08-29 08:20 UTC, josancamon19 commented
I would change the image, as it will not look great on the app.

2024-08-29 08:20 UTC, merged

2024-08-29 08:20 UTC, josancamon19 commented
![CleanShot 2024-08-29 at 01 20 33@2x](https://github.com/user-attachments/assets/01b177f4-e288-4a64-9e3a-50853d786e95)
Got this btw

2024-08-30 23:47 UTC, AlexTs10 commented
Will check, probably its because you didn't do the setup.

2024-09-05 23:51 UTC, AlexTs10 commented
Hey, i wanted to ask why i can't see the plugin in the app since it passed the pr ?