Documentation Update.
BasedHardware/omi pull request #918
Opened 2024-09-25 05:24 UTC by smian1

2024-09-30 00:45 UTC, josancamon19 requested changes

2024-09-30 00:45 UTC, josancamon19 commented on docs/_get_started/backend/security_measures.md
> +- Google Cloud Logging is used for centralized log collection and analysis.
is not, we actually host stuff in modal, there's some stuff logged surely on GCP, not even sure what, but we don't really look into it.

2024-09-30 00:45 UTC, josancamon19 commented on docs/_get_started/backend/transcription.md
> +After the real-time transcription is complete, speaker identification is performed using SpeechBrain's ECAPA-TDNN model:
we are not doing this anymore, 

We use soniox default speech recognition service.

2024-09-30 00:46 UTC, josancamon19 commented on docs/_get_started/backend/transcription.md
> +After the real-time transcription is complete, speaker identification is performed using SpeechBrain's ECAPA-TDNN model:
I mean, we were doing this, on previous postprocessing pipeline, which is not used anymore.

2024-09-30 00:46 UTC, josancamon19 commented on docs/_get_started/backend/security_measures.md
> +- Google Cloud Logging is used for centralized log collection and analysis.
Also, we don't store recordings anymore, as there's no training, as well as all previous recordings were deleted

2024-10-06 06:42 UTC, smian1 commented on docs/_get_started/backend/security_measures.md
> +- Google Cloud Logging is used for centralized log collection and analysis.
Since a lot of changes were made, I'm going to close this PR and try to submit one at a time so that it's a little more focused.

2024-10-06 06:42 UTC, closed without merging